name: Deploy Node.js App to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Get your code from GitHub
      - uses: actions/checkout@v3

      # 2. Set up SSH using your secret
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      # 3. Connect to EC2 and deploy
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            # Go to project folder or clone if not exists
            cd ~/PALMER-DEVOPS || git clone https://github.com/mrAUTHENTIC-18/PALMER-DEVOPS.git ~/PALMER-DEVOPS
            cd ~/PALMER-DEVOPS

            # Pull latest changes
            git pull origin main

            # Build Docker image
            docker build -t devops-container.

            # Stop & remove old container if exists
            docker stop devops-container || true
            docker rm devops-container || true

            # Run new container
            docker run -d -p 3000:3000 --name devops-container devops-container
          EOF
