name: Deploy Palmer DevOps App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_PUBLIC_IP }} << "
            set -e

            cd ~
            if [ ! -d "PALMER-DEVOPS" ]; then
              git clone https://github.com/mrAUTHENTIC-18/PALMER-DEVOPS.git
            fi

            cd PALMER-DEVOPS
            git pull origin main

            docker build -t palmerdevopsapp .

            docker stop palmerdevopsapp || true
            docker rm palmerdevopsapp || true

            docker run -d \
              --name palmerdevopsapp \
              -p 3000:3000 \
              palmerdevopsapp
                         "
